#!/usr/bin/env bash
time (cd "$(dirname "$(readlink -f "$0" 2>/dev/null)" 2>/dev/null)"
#fakechroot fakeroot chroot RunDir/rootfs pacman -Q > RunDir/packages 2>/dev/null
rm -rf RunDir/rootfs/var/lib/pacman/sync/*
rm -rf RunDir/rootfs/var/cache/pacman/pkg/*
rm -rf RunDir/rootfs/var/log/pacman.log
LOCALEFL=("de" "en" "en_US" "ru" "uk")
for loc in $(ls -1 RunDir/rootfs/usr/share/locale/)
     do
          [ "$loc" == "locale.alias" ] && continue
          if ! [[ "${LOCALEFL[@]}" =~ "$loc" ]]
               then
                    rm -rf "RunDir/rootfs/usr/share/locale/$loc"
          fi
done
LOCALEHLP=("C" "de" "en" "en_US" "ru" "uk")
for loc in $(ls -1 RunDir/rootfs/usr/share/help/)
     do
          if ! [[ "${LOCALEHLP[@]}" =~ "$loc" ]]
               then
                    rm -rf "RunDir/rootfs/usr/share/help/$loc"
          fi
done
#RunDir/rootfs/usr/share/qt/translation/*
#RunDir/rootfs/usr/share/i18n/locales/*
#RunDir/rootfs/usr/share/X11/locale/*

mksquashfs RunDir RunDir.lz4.sfs -root-owned -no-xattrs -noappend -b 256K -comp lz4 -Xhc -quiet && \
     cat runtime-fuse2-lz4 RunDir.lz4.sfs > runimage && \
     chmod +x runimage

# mksquashfs RunDir RunDir.zst.sfs -root-owned -no-xattrs -noappend -b 1M -comp zstd -Xcompression-level 19 -quiet && \
#      cat runtime-fuse2-zstd RunDir.zst.sfs > runimage.zst && \
#      chmod +x runimage.zst

# mksquashfs RunDir RunDir.xz.sfs -root-owned -no-xattrs -noappend -b 1M -comp xz -quiet && \
#      cat runtime-fuse2-all RunDir.xz.sfs > runimage.xz && \
#      chmod +x runimage.xz
)
