#!/usr/bin/env bash
shopt -s extglob

RUNIMAGE_VERSION='v0.39.1'

# disable nvidia driver check function
export RIM_NO_NVIDIA_CHECK=1

# download base runimage
if [[ ! -x 'runimage' && ! -x 'RunDir/Run' ]]
    then
        curl -LO "https://github.com/VHSgunzo/runimage/releases/download/$RUNIMAGE_VERSION/runimage"
        chmod +x runimage
fi

# extract base runimage
if [ ! -x 'RunDir/Run' ]
    then
        rm -rf RunDir
        ./runimage --runtime-extract
fi

# download shrinking script
if [ ! -x 'rim-shrink' ]
    then
        curl -LO "https://raw.githubusercontent.com/VHSgunzo/runimage/main/rim-shrink"
        chmod +x rim-shrink
fi

# create new runimage rootfs
rm -rf rootfs
mkdir rootfs

# update base runimage
./RunDir/Run rim-update
# install and fix pacstrap
./RunDir/Run sh -c "pac -S arch-install-scripts --noconfirm --needed && \
                    sed -i 's|\$setup \"\$newroot\"|# &|' /bin/pacstrap"

# bootstrap new runimage rootfs with base packages
./RunDir/Run sudo pacstrap -P rootfs \
    base runimage-mirrorlist fake-sudo-pkexec \
    fake-systemd fake-nvidia-driver fakeroot fakechroot \
    lib32-glibc lib32-fakeroot lib32-fakechroot \
    chaotic-keyring chaotic-mirrorlist dbus less \
    blackarch-keyring blackarch-mirrorlist which \
    iptables-nft nftables openresolv iputils

# rebase runimage utils
rm -rf new
mkdir -p new/RunDir
cp -r ./RunDir/!(rootfs) ./new/RunDir
mv rootfs ./new/RunDir/

(cd new

# fix os-release
[[ ! -f './RunDir/rootfs/etc/os-release' && -f './RunDir/rootfs/usr/lib/os-release' ]] && \
    ln -sfr ./RunDir/rootfs/usr/lib/os-release ./RunDir/rootfs/etc/os-release

# add runimage utils to pacman db
./RunDir/Run sudo pacman -S Run-wrapper runimage-utils \
    runimage-static --noconfirm --overwrite '*'

# fix locale
echo 'LANG=C.UTF-8' >> ./RunDir/rootfs/etc/locale.conf
./RunDir/Run pac -S glibc --noconfirm
./RunDir/Run locale-gen

# replace filesystem pkg with runimage-rootfs
rm -rf ./RunDir/rootfs/var/lib/pacman/local/filesystem-*
echo 'nameserver 8.8.8.8' >> ./RunDir/rootfs/etc/resolv.conf
./RunDir/static/bwrap --bind ./RunDir/rootfs / --proc /proc \
    --dev-bind /dev /dev --bind /sys /sys --tmpfs /run \
    --tmpfs /tmp pac -S runimage-rootfs --noconfirm

# optional to prevent container bloating after updates
# cp new pacman config
cp -f ../pacman.conf ./RunDir/rootfs/etc/pacman.conf

# optional for shrink
./RunDir/Run pac -Rsndd python perl --noconfirm

# install additional packages
#./RunDir/Run pac -S pkg pkg --noconfirm

# optional for shrink (remove lib32 packages)
./RunDir/Run pac -Rsndd lib32-glibc lib32-fakeroot lib32-fakechroot --noconfirm

# cleanup
../rim-shrink

# build new runimage
./RunDir/Run rim-build
)
