#!/usr/bin/env bash
shopt -s extglob

RUNIMAGE_VERSION='v0.39.1'

# disable nvidia driver check function
export RIM_NO_NVIDIA_CHECK=1

# download base runimage
if [[ ! -x 'runimage' && ! -x 'RunDir/Run' ]]
    then
        curl -LO "https://github.com/VHSgunzo/runimage/releases/download/$RUNIMAGE_VERSION/runimage"
        chmod +x runimage
fi

# extract base runimage
if [ ! -x 'RunDir/Run' ]
    then
        rm -rf RunDir
        ./runimage --runtime-extract
fi

# download shrinking script
if [ ! -x 'rim-shrink' ]
    then
        curl -LO "https://raw.githubusercontent.com/VHSgunzo/runimage/main/rim-shrink"
        chmod +x rim-shrink
fi

# create new runimage rootfs
rm -rf rootfs
mkdir rootfs

# update base runimage
./RunDir/Run rim-update
# install and fix pacstrap
./RunDir/Run sh -c "pac -S arch-install-scripts --noconfirm --needed && \
                    sed -i 's|\$setup \"\$newroot\"|# &|' /bin/pacstrap"

# bootstrap new runimage rootfs with base packages
./RunDir/Run sudo pacstrap -P rootfs \
    base runimage-mirrorlist fake-sudo-pkexec \
    fake-systemd fake-nvidia-driver fakeroot fakechroot \
    lib32-glibc lib32-fakeroot lib32-fakechroot \
    chaotic-keyring chaotic-mirrorlist dbus less \
    blackarch-keyring blackarch-mirrorlist which \
    iptables-nft nftables openresolv iputils

# rebase runimage utils
rm -rf new
mkdir -p new/RunDir
cp -r ./RunDir/!(rootfs) ./new/RunDir
mv rootfs ./new/RunDir/

(cd new

SHRINK_ITEMS=(
    ./RunDir/rootfs/usr/share/libalpm/hooks/*systemd*
    ./RunDir/rootfs/usr/share/libalpm/scripts/*systemd*
    ./RunDir/rootfs/usr/share/libalpm/hooks/dbus-reload.hook
    ./RunDir/rootfs/etc/bash_completion.d/megacmd_completion.sh
    ./RunDir/rootfs/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
    ./RunDir/rootfs/usr/share/libalpm/hooks/60-depmod.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/60-mkinitcpio-remove.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/70-dkms-install.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/70-dkms-upgrade.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/71-dkms-remove.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/90-mkinitcpio-install.hook
    ./RunDir/rootfs/usr/share/libalpm/hooks/grub.hook
    ./RunDir/rootfs/usr/share/libalpm/scripts/depmod
    ./RunDir/rootfs/usr/share/libalpm/scripts/dkms
    ./RunDir/rootfs/usr/share/libalpm/scripts/mkinitcpio
    ./RunDir/rootfs/usr/share/libalpm/hooks/90-update-appstream-cache.hook
    ./RunDir/rootfs/usr/include/*
    ./RunDir/rootfs/usr/share/doc/*
    ./RunDir/rootfs/usr/share/man/*
    ./RunDir/rootfs/usr/share/info/*
    ./RunDir/rootfs/usr/share/help/*
    ./RunDir/rootfs/usr/share/gtk-doc/*
    ./RunDir/rootfs/usr/lib/*.a
    ./RunDir/rootfs/usr/lib32/*.a
    ./RunDir/rootfs/usr/share/locale/ab/*
    ./RunDir/rootfs/usr/share/locale/ach/*
    ./RunDir/rootfs/usr/share/locale/af/*
    ./RunDir/rootfs/usr/share/locale/ain/*
    ./RunDir/rootfs/usr/share/locale/am/*
    ./RunDir/rootfs/usr/share/locale/an/*
    ./RunDir/rootfs/usr/share/locale/ang/*
    ./RunDir/rootfs/usr/share/locale/ar/*
    ./RunDir/rootfs/usr/share/locale/as/*
    ./RunDir/rootfs/usr/share/locale/ast/*
    ./RunDir/rootfs/usr/share/locale/az/*
    ./RunDir/rootfs/usr/share/locale/az_IR/*
    ./RunDir/rootfs/usr/share/locale/bar/*
    ./RunDir/rootfs/usr/share/locale/be/*
    ./RunDir/rootfs/usr/share/locale/be@latin/*
    ./RunDir/rootfs/usr/share/locale/ber/*
    ./RunDir/rootfs/usr/share/locale/bg/*
    ./RunDir/rootfs/usr/share/locale/bg_BG/*
    ./RunDir/rootfs/usr/share/locale/bn/*
    ./RunDir/rootfs/usr/share/locale/bn_BD/*
    ./RunDir/rootfs/usr/share/locale/bn_IN/*
    ./RunDir/rootfs/usr/share/locale/bo/*
    ./RunDir/rootfs/usr/share/locale/br/*
    ./RunDir/rootfs/usr/share/locale/brx/*
    ./RunDir/rootfs/usr/share/locale/bs/*
    ./RunDir/rootfs/usr/share/locale/ca/*
    ./RunDir/rootfs/usr/share/locale/ca_ES@valencia/*
    ./RunDir/rootfs/usr/share/locale/ca.us-ascii/*
    ./RunDir/rootfs/usr/share/locale/ca@valencia/*
    ./RunDir/rootfs/usr/share/locale/ce/*
    ./RunDir/rootfs/usr/share/locale/chr/*
    ./RunDir/rootfs/usr/share/locale/ckb/*
    ./RunDir/rootfs/usr/share/locale/cmn/*
    ./RunDir/rootfs/usr/share/locale/co/*
    ./RunDir/rootfs/usr/share/locale/crh/*
    ./RunDir/rootfs/usr/share/locale/cs/*
    ./RunDir/rootfs/usr/share/locale/csb/*
    ./RunDir/rootfs/usr/share/locale/cs_CZ/*
    ./RunDir/rootfs/usr/share/locale/cy/*
    ./RunDir/rootfs/usr/share/locale/da/*
    ./RunDir/rootfs/usr/share/locale/de/*
    ./RunDir/rootfs/usr/share/locale/de_CH/*
    ./RunDir/rootfs/usr/share/locale/de_DE/*
    ./RunDir/rootfs/usr/share/locale/de@hebrew/*
    ./RunDir/rootfs/usr/share/locale/de.us-ascii/*
    ./RunDir/rootfs/usr/share/locale/doi/*
    ./RunDir/rootfs/usr/share/locale/dz/*
    ./RunDir/rootfs/usr/share/locale/el/*
    ./RunDir/rootfs/usr/share/locale/en@arabic/*
    ./RunDir/rootfs/usr/share/locale/en_AU/*
    ./RunDir/rootfs/usr/share/locale/en@boldquot/*
    ./RunDir/rootfs/usr/share/locale/en_CA/*
    ./RunDir/rootfs/usr/share/locale/en@cyrillic/*
    ./RunDir/rootfs/usr/share/locale/en_ee/*
    ./RunDir/rootfs/usr/share/locale/en_GB/*
    ./RunDir/rootfs/usr/share/locale/en@greek/*
    ./RunDir/rootfs/usr/share/locale/en@hebrew/*
    ./RunDir/rootfs/usr/share/locale/en_NZ/*
    ./RunDir/rootfs/usr/share/locale/en@piglatin/*
    ./RunDir/rootfs/usr/share/locale/en@quot/*
    ./RunDir/rootfs/usr/share/locale/en@shaw/*
    ./RunDir/rootfs/usr/share/locale/eo/*
    ./RunDir/rootfs/usr/share/locale/es/*
    ./RunDir/rootfs/usr/share/locale/es_419/*
    ./RunDir/rootfs/usr/share/locale/es_AR/*
    ./RunDir/rootfs/usr/share/locale/es_MX/*
    ./RunDir/rootfs/usr/share/locale/es_VE/*
    ./RunDir/rootfs/usr/share/locale/et/*
    ./RunDir/rootfs/usr/share/locale/eu/*
    ./RunDir/rootfs/usr/share/locale/fa/*
    ./RunDir/rootfs/usr/share/locale/fa_IR/*
    ./RunDir/rootfs/usr/share/locale/fi/*
    ./RunDir/rootfs/usr/share/locale/fi_FI/*
    ./RunDir/rootfs/usr/share/locale/fo/*
    ./RunDir/rootfs/usr/share/locale/fr/*
    ./RunDir/rootfs/usr/share/locale/fr_CA/*
    ./RunDir/rootfs/usr/share/locale/fr_FR/*
    ./RunDir/rootfs/usr/share/locale/fur/*
    ./RunDir/rootfs/usr/share/locale/fy/*
    ./RunDir/rootfs/usr/share/locale/ga/*
    ./RunDir/rootfs/usr/share/locale/gd/*
    ./RunDir/rootfs/usr/share/locale/gl/*
    ./RunDir/rootfs/usr/share/locale/gl_ES/*
    ./RunDir/rootfs/usr/share/locale/gr/*
    ./RunDir/rootfs/usr/share/locale/gu/*
    ./RunDir/rootfs/usr/share/locale/guc/*
    ./RunDir/rootfs/usr/share/locale/gug_PY/*
    ./RunDir/rootfs/usr/share/locale/ha/*
    ./RunDir/rootfs/usr/share/locale/he/*
    ./RunDir/rootfs/usr/share/locale/he_IL/*
    ./RunDir/rootfs/usr/share/locale/hi/*
    ./RunDir/rootfs/usr/share/locale/hne/*
    ./RunDir/rootfs/usr/share/locale/hr/*
    ./RunDir/rootfs/usr/share/locale/hrx/*
    ./RunDir/rootfs/usr/share/locale/hsb/*
    ./RunDir/rootfs/usr/share/locale/hu/*
    ./RunDir/rootfs/usr/share/locale/hu_HU/*
    ./RunDir/rootfs/usr/share/locale/hy/*
    ./RunDir/rootfs/usr/share/locale/hye/*
    ./RunDir/rootfs/usr/share/locale/ia/*
    ./RunDir/rootfs/usr/share/locale/id/*
    ./RunDir/rootfs/usr/share/locale/id_ID/*
    ./RunDir/rootfs/usr/share/locale/ie/*
    ./RunDir/rootfs/usr/share/locale/io/*
    ./RunDir/rootfs/usr/share/locale/is/*
    ./RunDir/rootfs/usr/share/locale/it/*
    ./RunDir/rootfs/usr/share/locale/it_IT/*
    ./RunDir/rootfs/usr/share/locale/ja/*
    ./RunDir/rootfs/usr/share/locale/ja_JP/*
    ./RunDir/rootfs/usr/share/locale/jam/*
    ./RunDir/rootfs/usr/share/locale/ka/*
    ./RunDir/rootfs/usr/share/locale/kab/*
    ./RunDir/rootfs/usr/share/locale/kf5_all_languages/*
    ./RunDir/rootfs/usr/share/locale/kg/*
    ./RunDir/rootfs/usr/share/locale/kk/*
    ./RunDir/rootfs/usr/share/locale/km/*
    ./RunDir/rootfs/usr/share/locale/km_KH/*
    ./RunDir/rootfs/usr/share/locale/kmr/*
    ./RunDir/rootfs/usr/share/locale/kn/*
    ./RunDir/rootfs/usr/share/locale/ko/*
    ./RunDir/rootfs/usr/share/locale/kok/*
    ./RunDir/rootfs/usr/share/locale/kok@latin/*
    ./RunDir/rootfs/usr/share/locale/ko_KR/*
    ./RunDir/rootfs/usr/share/locale/ks@aran/*
    ./RunDir/rootfs/usr/share/locale/ks@deva/*
    ./RunDir/rootfs/usr/share/locale/ku/*
    ./RunDir/rootfs/usr/share/locale/ky/*
    ./RunDir/rootfs/usr/share/locale/la/*
    ./RunDir/rootfs/usr/share/locale/lb/*
    ./RunDir/rootfs/usr/share/locale/lg/*
    ./RunDir/rootfs/usr/share/locale/li/*
    ./RunDir/rootfs/usr/share/locale/lo/*
    ./RunDir/rootfs/usr/share/locale/lo_LA/*
    ./RunDir/rootfs/usr/share/locale/lt/*
    ./RunDir/rootfs/usr/share/locale/lt_LT/*
    ./RunDir/rootfs/usr/share/locale/lv/*
    ./RunDir/rootfs/usr/share/locale/lv_LV/*
    ./RunDir/rootfs/usr/share/locale/mai/*
    ./RunDir/rootfs/usr/share/locale/mg/*
    ./RunDir/rootfs/usr/share/locale/mhr/*
    ./RunDir/rootfs/usr/share/locale/mi/*
    ./RunDir/rootfs/usr/share/locale/mjw/*
    ./RunDir/rootfs/usr/share/locale/mk/*
    ./RunDir/rootfs/usr/share/locale/mk_MK/*
    ./RunDir/rootfs/usr/share/locale/ml/*
    ./RunDir/rootfs/usr/share/locale/ml_IN/*
    ./RunDir/rootfs/usr/share/locale/mn/*
    ./RunDir/rootfs/usr/share/locale/mni/*
    ./RunDir/rootfs/usr/share/locale/mni@beng/*
    ./RunDir/rootfs/usr/share/locale/mo/*
    ./RunDir/rootfs/usr/share/locale/mr/*
    ./RunDir/rootfs/usr/share/locale/ms/*
    ./RunDir/rootfs/usr/share/locale/mt/*
    ./RunDir/rootfs/usr/share/locale/mus/*
    ./RunDir/rootfs/usr/share/locale/my/*
    ./RunDir/rootfs/usr/share/locale/nah/*
    ./RunDir/rootfs/usr/share/locale/nap/*
    ./RunDir/rootfs/usr/share/locale/nb/*
    ./RunDir/rootfs/usr/share/locale/nb_NO/*
    ./RunDir/rootfs/usr/share/locale/nds/*
    ./RunDir/rootfs/usr/share/locale/ne/*
    ./RunDir/rootfs/usr/share/locale/nl/*
    ./RunDir/rootfs/usr/share/locale/nn/*
    ./RunDir/rootfs/usr/share/locale/nn_NO/*
    ./RunDir/rootfs/usr/share/locale/no.us-ascii/*
    ./RunDir/rootfs/usr/share/locale/nqo/*
    ./RunDir/rootfs/usr/share/locale/nso/*
    ./RunDir/rootfs/usr/share/locale/oc/*
    ./RunDir/rootfs/usr/share/locale/or/*
    ./RunDir/rootfs/usr/share/locale/pa/*
    ./RunDir/rootfs/usr/share/locale/pl/*
    ./RunDir/rootfs/usr/share/locale/pl_PL/*
    ./RunDir/rootfs/usr/share/locale/pms/*
    ./RunDir/rootfs/usr/share/locale/ps/*
    ./RunDir/rootfs/usr/share/locale/pt/*
    ./RunDir/rootfs/usr/share/locale/pt_BR/*
    ./RunDir/rootfs/usr/share/locale/pt_BR.us-ascii/*
    ./RunDir/rootfs/usr/share/locale/pt_PT/*
    ./RunDir/rootfs/usr/share/locale/pt.us-ascii/*
    ./RunDir/rootfs/usr/share/locale/ro/*
    ./RunDir/rootfs/usr/share/locale/rom/*
    ./RunDir/rootfs/usr/share/locale/ro_RO/*
    ./RunDir/rootfs/usr/share/locale/rue/*
    ./RunDir/rootfs/usr/share/locale/rw/*
    ./RunDir/rootfs/usr/share/locale/sa/*
    ./RunDir/rootfs/usr/share/locale/sat/*
    ./RunDir/rootfs/usr/share/locale/sat@deva/*
    ./RunDir/rootfs/usr/share/locale/sd/*
    ./RunDir/rootfs/usr/share/locale/sd@deva/*
    ./RunDir/rootfs/usr/share/locale/se/*
    ./RunDir/rootfs/usr/share/locale/shn/*
    ./RunDir/rootfs/usr/share/locale/si/*
    ./RunDir/rootfs/usr/share/locale/sk/*
    ./RunDir/rootfs/usr/share/locale/sk_SK/*
    ./RunDir/rootfs/usr/share/locale/sl/*
    ./RunDir/rootfs/usr/share/locale/sl_SI/*
    ./RunDir/rootfs/usr/share/locale/sma/*
    ./RunDir/rootfs/usr/share/locale/son/*
    ./RunDir/rootfs/usr/share/locale/sq/*
    ./RunDir/rootfs/usr/share/locale/sr/*
    ./RunDir/rootfs/usr/share/locale/sr_Cyrl/*
    ./RunDir/rootfs/usr/share/locale/sr@ije/*
    ./RunDir/rootfs/usr/share/locale/sr@ijekavian/*
    ./RunDir/rootfs/usr/share/locale/sr@ijekavianlatin/*
    ./RunDir/rootfs/usr/share/locale/sr@latin/*
    ./RunDir/rootfs/usr/share/locale/sr_RS/*
    ./RunDir/rootfs/usr/share/locale/sv/*
    ./RunDir/rootfs/usr/share/locale/sw/*
    ./RunDir/rootfs/usr/share/locale/szl/*
    ./RunDir/rootfs/usr/share/locale/ta/*
    ./RunDir/rootfs/usr/share/locale/te/*
    ./RunDir/rootfs/usr/share/locale/tg/*
    ./RunDir/rootfs/usr/share/locale/th/*
    ./RunDir/rootfs/usr/share/locale/th_TH/*
    ./RunDir/rootfs/usr/share/locale/tk/*
    ./RunDir/rootfs/usr/share/locale/tok/*
    ./RunDir/rootfs/usr/share/locale/tr/*
    ./RunDir/rootfs/usr/share/locale/tt/*
    ./RunDir/rootfs/usr/share/locale/tzm/*
    ./RunDir/rootfs/usr/share/locale/ug/*
    ./RunDir/rootfs/usr/share/locale/ur/*
    ./RunDir/rootfs/usr/share/locale/uz/*
    ./RunDir/rootfs/usr/share/locale/uz@cyrillic/*
    ./RunDir/rootfs/usr/share/locale/vi/*
    ./RunDir/rootfs/usr/share/locale/vi_VN/*
    ./RunDir/rootfs/usr/share/locale/wa/*
    ./RunDir/rootfs/usr/share/locale/xh/*
    ./RunDir/rootfs/usr/share/locale/yi/*
    ./RunDir/rootfs/usr/share/locale/zgh/*
    ./RunDir/rootfs/usr/share/locale/zh/*
    ./RunDir/rootfs/usr/share/locale/zh_CN/*
    ./RunDir/rootfs/usr/share/locale/zh_Hans/*
    ./RunDir/rootfs/usr/share/locale/zh_Hant/*
    ./RunDir/rootfs/usr/share/locale/zh_HK/*
    ./RunDir/rootfs/usr/share/locale/zh_TW/*
    ./RunDir/rootfs/usr/share/locale/zu/*
    ./RunDir/rootfs/usr/share/locale/az_AZ/*
    ./RunDir/rootfs/usr/share/locale/eu_ES/*
    ./RunDir/rootfs/usr/share/locale/hy_AM/*
    ./RunDir/rootfs/usr/share/locale/ur_PK/*
)

# fix os-release
[[ ! -f './RunDir/rootfs/etc/os-release' && -f './RunDir/rootfs/usr/lib/os-release' ]] && \
    ln -sfr ./RunDir/rootfs/usr/lib/os-release ./RunDir/rootfs/etc/os-release

# add runimage utils to pacman db
./RunDir/Run sudo pacman -S Run-wrapper runimage-utils \
    runimage-static --noconfirm --overwrite '*'

# fix locale
echo 'LANG=C.UTF-8' >> ./RunDir/rootfs/etc/locale.conf
./RunDir/Run pac -S glibc --noconfirm
./RunDir/Run locale-gen

# replace filesystem pkg with runimage-rootfs
rm -rf ./RunDir/rootfs/var/lib/pacman/local/filesystem-*
echo 'nameserver 8.8.8.8' >> ./RunDir/rootfs/etc/resolv.conf
./RunDir/static/bwrap --bind ./RunDir/rootfs / --proc /proc \
    --dev-bind /dev /dev --bind /sys /sys --tmpfs /run \
    --tmpfs /tmp pac -S runimage-rootfs --noconfirm

# optional to prevent container bloating after updates
# cp new pacman config
cp -f ../pacman.conf ./RunDir/rootfs/etc/pacman.conf

# optional for shrink
./RunDir/Run pac -Rsndd python perl --noconfirm

# install additional packages
#./RunDir/Run pac -S pkg pkg --noconfirm

# optional for shrink (remove lib32 packages)
./RunDir/Run pac -Rsndd lib32-glibc lib32-fakeroot lib32-fakechroot --noconfirm

# optional for shrink
../rim-shrink

# optional for shrink
rm -rf "${SHRINK_ITEMS[@]}"

# cleanup
rm -rf ./RunDir/rootfs/{dev,sys,proc,tmp,run}/*
rm -f RunDir/rootfs/etc/pacman.d/gnupg/S.*

# build new runimage
./RunDir/Run rim-build
)
