#!/usr/bin/env bash
shopt -s extglob
if [ -d RunDir ]
    then
        if [ -f RunDir/cryptfs/gocryptfs.conf ]
            then
                if [ -d rootfs ]
                    then unset rundir
                    else
                        echo "rootfs encrypted and not mounted!"
                        exit 1
                fi
            else rundir='RunDir/'
        fi
        rm -rvf ${rundir}rootfs/usr/share/locale/!(locale.alias|uk|ru|en|en_US)
        rm -rvf ${rundir}rootfs/usr/share/gtk-doc/*
        rm -rvf ${rundir}rootfs/usr/share/man/*
        rm -rvf ${rundir}rootfs/usr/share/help/*
        rm -rvf ${rundir}rootfs/usr/share/info/*
        rm -rvf ${rundir}rootfs/usr/share/doc/*
        find ${rundir}rootfs/ -type d -name '__pycache__' -exec rm -rvf {} \;
        find ${rundir}rootfs/ -type f -name '*.pacnew' -exec rm -rvf {} \;
        find ${rundir}rootfs/ -type f -name '*.pacsave' -exec rm -rvf {} \;
        find ${rundir}rootfs/var/log/ -type f -name '*.log' -exec rm -rvf {} \;
        rm -rvf ${rundir}rootfs/var/tmp/*
        rm -rvf ${rundir}rootfs/var/lib/pacman/sync/*
        rm -rvf ${rundir}rootfs/var/cache/pacman/pkg/*
        rm -rvf ${rundir}rootfs/var/lib/pacman/db.lck
        rm -rvf ${rundir}rootfs/etc/pacman.d/gnupg/pubring.gpg~
        rm -rf ${rundir}rootfs/var/cache/apt/archives/*.deb
        rm -rf ${rundir}rootfs/var/cache/apt/*.bin
        rm -rf ${rundir}rootfs/var/lib/apt/lists/deb.*
        rm -rf ${rundir}rootfs/var/log/apt/*
        nv_version="$(cat /sys/module/nvidia/version 2>/dev/null)"
        [ -n "$nv_version"  ] && \
            find ${rundir}rootfs/ -name "*so.$nv_version" -exec rm -rvf {} \;
        if [ -f ${rundir}rootfs/etc/ld.so.version ]
            then
                echo "Found ld.so.version!"
                rm -rvf ${rundir}rootfs/etc/ld.so.version
                NO_NVIDIA_CHECK=1 QUIET_MODE=1 ALLOW_BG=0 SANDBOX_NET=0 \
                    RunDir/Run ldconfig
         fi
    else
        echo "RunDir not found!"
        exit 1
fi
