#!/usr/bin/bash

mv /usr/bin/ldconfig /usr/bin/_ldconfig
echo '#!/usr/bin/env sh
if [ -x /run/host/usr/sbin/_ldconfig ]
    then exec /run/host/usr/sbin/_ldconfig "$@" 2>/dev/null
    else exec _ldconfig "$@" 2>/dev/null
fi' > /usr/bin/ldconfig
chmod +x /usr/bin/ldconfig
