#!/usr/bin/bash

shopt -s extglob

RED='\033[1;91m'
BLUE='\033[1;94m'
GREEN='\033[1;92m'
YELLOW='\033[1;33m'
RESETCOLOR='\033[1;00m'

nocolor() { sed -r 's|\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]||g' ; }

error_msg() {
    echo -e "${RED}[ ERROR ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
    if [ "$NOT_TERM" == 1 ]
        then notify-send -a 'RunImage Error' "$(echo -e "$@"|nocolor)" 2>/dev/null &
    fi
}

info_msg() {
    if [ "$QUIET_MODE" != 1 ]
        then
            echo -e "${GREEN}[ INFO ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
            if [[ "$NOT_TERM" == 1 && "$DONT_NOTIFY" != 1 ]]
                then notify-send -a 'RunImage Info' "$(echo -e "$@"|nocolor)" 2>/dev/null &
            fi
    fi
}

bad_tmp() { error_msg "BWINFFL not found! Something is wrong with /tmp" ; }

[ ! -n "$(tty|grep -v 'not a'|grep -Eo 'tty|pts')" ] && \
    NOT_TERM=1

if [ -n "$OVERFS_MNT" ]
    then
        if [[ -d "$RUNDIR" && -d "$OVERFS_MNT" ]]
            then
                info_msg "RunDir update..."
                cp -rf "$OVERFS_DIR/layers"/!(rootfs|.unionfs) "$RUNDIR"
            else
                if [ -f "$BWINFFL" ]
                    then
                        info_msg "RunDir will be updated!"
                        touch "/tmp/.r$RUNPID.copy"
                    else bad_tmp
                fi
        fi
fi
