#!/usr/bin/bash

HINTEG_DIR="$HOME/.local/share"
HINTEG_APPS_DIR="$HINTEG_DIR/applications"
ICONS_DIR='/usr/share/icons'
APPS_DIR='/usr/share/applications'

[ -f "$RIMENVFL" ] && \
    source "$RIMENVFL"

IGNORE_FILES=(
    'mimeinfo.cache'
    'icon-theme.cache'
)
INTEG_DIRS=(
    "$APPS_DIR"
    "$ICONS_DIR"/*.svg
    "$ICONS_DIR"/*.png
    "$ICONS_DIR/hicolor"
    '/usr/share/desktop-directories'
    '/etc/xdg/menus/applications-merged'
)
MIME_DIRS=(
    '/usr/share/mime/packages'
    '/usr/share/mime/inode'
    '/usr/share/mime/text'
    '/usr/share/mime/application'
    '/usr/share/mime/model'
    '/usr/share/mime/video'
    '/usr/share/mime/font'
    '/usr/share/mime/image'
    '/usr/share/mime/audio'
    '/usr/share/mime/multipart'
    '/usr/share/mime/x-content'
    '/usr/share/mime/message'
    '/usr/share/mime/chemical'
    '/usr/share/mime/x-epoc'
)

lsapps() {
    local apps="$(grep -m1 '^Name=' -nr "$APPS_DIR" 2>/dev/null|\
                  sed 's|.*:Name=||g;s|.*|"&"|g'|sort)"
    [ -n "$apps" ] && cat -n<<<"$apps"
}

lsintegapps() {
    local apps="$(grep -m1 '^Name=.* \[RunImage\]' -nr "$HINTEG_APPS_DIR"/*-rimg.desktop 2>/dev/null|\
                  sed 's|.*:Name=||g;s| \[RunImage\]$||g;s|.*|"&"|g'|sort)"
    [ -n "$apps" ] && cat -n<<<"$apps"
}

find_fl() { find "$@" -type f 2>/dev/null|sort ; }

upd_ddb() { update-desktop-database -q "$HINTEG_APPS_DIR" &>/dev/null ; }

upd_mdb() { update-mime-database "$HINTEG_DIR/mime" &>/dev/null ; }

dinteg() {
    while read -r file
        do
            [[ ! "${IGNORE_FILES[@]}" =~ "$(basename "$file")" ]]||\
                continue
            [ "${file:0:1}" == '/' ]||\
                file="/${file}"
            if [ -f "$file" ]
                then
                    unset postfix postfix_dir target exec_args
                    target="$(awk -F/ '{print$4}'<<<"$file")"
                    postfix="$(cut -d'/' -f4-<<<"$file"|sed 's|.desktop$|-rimg.desktop|i;s|.png$|-rimg.png|i;s|.svg$|-rimg.svg|i;s|.xml$|-rimg.xml|i')"
                    postfix_dir="$(dirname "$postfix")"
                    [ "$target" == 'menus' ] && \
                        HINTEG_DIR="$HOME/.config"
                    hinteg_file="${HINTEG_DIR}/${postfix}"
                    hinteg_file_dir="${HINTEG_DIR}/${postfix_dir}"
                    case "$act" in
                        i)
                            mkdir $verb -p "$hinteg_file_dir"
                            cp $verb -f "$file" "$hinteg_file"

                            if [[ "$hinteg_file" == *'.desktop' ]]
                                then
                                    exec_args="env "
                                    [ -n "$RIM_OVERFS_ID" ] && \
                                    exec_args+="RIM_OVERFS_ID='$RIM_OVERFS_ID' "
                                    #if [[ "$RUNSRCNAME" == "Run"* || \
                                    #      "$RUNSRCNAME" == "runimage"* ]]
                                    #    then exec_args+="'$RUNSRC' "
                                    #fi
                                    exec_args+="'$RUNSRC' "

                                    sed -i "s|^Icon.*|&-rimg|g;s|^Name.*|& [RunImage]|g;s|^Exec=|Exec=$exec_args|g;/^TryExec/d" "$hinteg_file"
                                    chmod +x "$hinteg_file"
                            fi
                        ;;
                        r)
                            [ -f "$hinteg_file" ] && \
                                rm $verb -f "$hinteg_file"
                        ;;
                        *) return 1 ;;
                    esac
            fi
    done
}

unset act ret
case "$1" in
    list|ls|l) shift
            ret=1
            case "$1" in
                install|in|i) lsintegapps ;;
                *) lsapps ;;
            esac
            if [ "$?" == 0 ]
                then ret=0
                else echo "No apps found!"
            fi
            exit $ret
        ;;
    install|in|i) shift ; act=i ;;
    remove|rm|r) shift ; act=r ;;
    *) echo "Unknown argument!" ; exit 1 ;;
esac

if [ -n "$1" ]
    then
        verb='-v'
        case "$1" in
            hook) shift
                unset verb
                if [ "$RIM_DESKTOP_INTEGRATION" == 1 ]
                    then dinteg
                    else echo "Desktop integration is disabled!"
                fi
            ;;
            all) shift
                [ "$RIM_DINTEG_WITH_MIME" == 1 ] && \
                    INTEG_DIRS+=("${MIME_DIRS[@]}")
                find_fl "${INTEG_DIRS[@]}"|dinteg
                upd_ddb
                [ "$RIM_DINTEG_WITH_MIME" == 1 ] && upd_mdb
            ;;
            mime) shift
                find_fl "${MIME_DIRS[@]}"|dinteg
                upd_mdb
            ;;
            *)  IFS=$'\n'
                app_list="$(case "$act" in
                    i) lsapps ;;
                    r) lsintegapps ;;
                esac)"
                for app in "$@"
                    do
                        (if [[ "$app" =~ ^[0-9]+$ ]]
                            then app_name="$(awk '($1 == "'$app'")'<<<"$app_list"|awk '{$1=""}1'|sed 's|"||g'|sed 's|^ ||g')"
                            else app_name="$app"
                        fi
                        integ_files=("$(grep -wm1 "^Name=$app_name$" -lr "$APPS_DIR" 2>/dev/null|head -1)")
                        if [ -n "$integ_files" ]
                            then
                                echo "[ $app_name ]:"
                                icon_name="$(grep -m1 "^Icon=" "$integ_files" 2>/dev/null|sed 's|^Icon=||')"
                                integ_files+=($(find_fl "$ICONS_DIR" -name "${icon_name}.*" 2>/dev/null))
                                for file in "${integ_files[@]}";do echo "$file";done|dinteg
                            else
                                echo "The app was not found!"
                                exit 1
                        fi)
                done
            ;;
        esac
    else
        echo "Specify the name or number of the app!"
        exit 1
fi
