#!/usr/bin/env bash

RED='\033[1;91m'
BLUE='\033[1;94m'
GREEN='\033[1;92m'
YELLOW='\033[1;33m'
RESETCOLOR='\033[1;00m'

[ -f "$RIMENVFL" ] && \
    source "$RIMENVFL"

[[ ! "$RUNTTY" =~ tty|pts ]] && \
    NOT_TERM=1||NOT_TERM=0

export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11
export DESKTOP_KEY="$BASHPID"
export SYS_DISPLAY="$DISPLAY"
RIM_DESKTOP_DISPLAY="${RIM_DESKTOP_DISPLAY:=1337}"

nocolor() { sed -r 's|\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]||g' ; }

error_msg() {
    echo -e "${RED}[ ERROR ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
    if [ "$NOT_TERM" == 1 ]
        then notify-send -a 'RunImage Error' "$(echo -e "$@"|nocolor)" 2>/dev/null &
    fi
}

info_msg() {
    if [ "$RIM_QUIET_MODE" != 1 ]
        then echo -e "${GREEN}[ INFO ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
            if [[ "$NOT_TERM" == 1 && "$RIM_NOTIFY" == 1 ]]
                then notify-send -a 'RunImage Info' "$(echo -e "$@"|nocolor)" 2>/dev/null &
            fi
    fi
}

warn_msg() {
    if [[ "$RIM_QUIET_MODE" != 1 && "$RIM_NO_WARN" != 1 ]]
        then echo -e "${YELLOW}[ WARNING ][$(date +"%Y.%m.%d %T")]: $@ $RESETCOLOR"
            if [[ "$NOT_TERM" == 1 && "$RIM_NOTIFY" == 1 ]]
                then notify-send -a 'RunImage Warning' "$(echo -e "$@"|nocolor)" 2>/dev/null &
            fi
    fi
}

is_exe_exist() { command -v "$@" &>/dev/null ; }

is_not_ro() {
    if [ ! -w "$RUNROOTFS" ]
        then
            error_msg "Unable to install dependencies. Read-only!"
            exit 1
    fi
}

is_pid() { [[ -n "$1" && -d "/proc/$1" ]]; }

empty_msg() {
    error_msg "${YELLOW}Option ${BLUE}$1 ${YELLOW}requires a non-empty argument!\n"
    print_help
}

print_help() {
    echo -e "[ Usage ]: rim-desktop [OPTIONS]

[ Options ]:
    -d, --display       Sets \$DISPLAY (env: RIM_DESKTOP_DISPLAY=1337)
    -f, --fullscreen    Starts Xephyr in fullscreen mode (env: RIM_XEPHYR_FULLSCREEN=1)
    -h, --help          Show this message
    -s, --size          Sets Xephyr resolution (env: RIM_XEPHYR_SIZE=1600x900)
    -u, --unclip        Disables clipboard synchronization (env: RIM_DESKTOP_UNCLIP=1)"
    exit 1
}

while [[ $# -gt 0 ]]
    do
        case "$1" in
            -h|--help      ) print_help ;;
            -f|--fullscreen) RIM_XEPHYR_FULLSCREEN=1 ;;
            -u|--unclip    ) RIM_DESKTOP_UNCLIP=1 ;;
            -d|--display   )
                if [[ -n "$2" && "$2" != -* ]]
                    then RIM_DESKTOP_DISPLAY="$2"; shift
                    else empty_msg "$1"
                fi ;;
            -s|--size      )
                if [[ -n "$2" && "$2" != -* ]]
                    then RIM_XEPHYR_SIZE="$2"; shift
                    else empty_msg "$1"
                fi ;;
            -*) error_msg "Unknown parameter: ${BLUE}$1\n"; print_help ;;
        esac
        shift
done

if [[ "$RUNTTY" =~ "tty" && ! -d '/run/udev' ]]
    then
        error_msg "/run/udev not found in RunImage container!"
        [ "$RIM_FORCE_KILL_PPID" != 1 ]||sleep 3
        exit 1
elif [[ "$RIM_UNSHARE_DBUS" != 1 || "$RIM_UNSHARE_PIDS" != 1 ]]||\
     [[ "$RUNTTY" =~ "tty" && "$RIM_FORCE_KILL_PPID" != 1 ]]
    then
        error_msg "Launch the RunImage desktop from the outside!"
        echo -e "$GREEN$ $RUNSRCNAME rim-desktop"
        exit 1
fi

[[ "$INSIDE_RUNIMAGE" == 1 && ! -d "$RUNROOTFS" ]] && \
     RUNROOTFS='/'

if is_exe_exist pacman
    then
        if [ "$(pacman -Qq xorg-server tk tcl xclip xfce4-session pavucontrol pulseaudio qt5ct 2>/dev/null|wc -l)" != "8" ] && is_not_ro
            then
                info_msg "Installing the necessary dependencies..."
                pac -Syu --noconfirm && \
                pac --needed --noconfirm -S xorg tk tcl xclip xfce4 xfce4-goodies pavucontrol pulseaudio qt5ct && \
                pac --noconfirm -Rdd xfce4-screensaver xfce4-power-manager||\
                exit 1
        fi
elif is_exe_exist apt
    then
        if [ "$(dpkg --get-selections|awk '{print$1}'|\
                grep -Ew '^xserver-xorg$|^xserver-xephyr$|^tk$|^tcl$|^xclip$|^xfce4-session$|^pavucontrol$|^pulseaudio$|^qt5ct$'|\
                wc -l)" != "9" ] && is_not_ro
            then
                info_msg "Installing the necessary dependencies..."
                sudo apt update && \
                sudo apt upgrade -y && \
                sudo apt install task-xfce-desktop xorg tk tcl xclip xfce4 \
                    xfce4-goodies pavucontrol pulseaudio xserver-xephyr qt5ct -y||\
                exit 1
        fi
else
    error_msg "The package manager cannot be detected!"
    exit 1
fi

[ ! -e '/usr/bin/pm-is-supported' ] && \
ln -sf /usr/bin/false /usr/bin/pm-is-supported

# PID randomizer (UNSHARE_PIDS ICEauthority bug)
[ "$RIM_UNSHARE_PIDS" == 1 ] && \
    for _ in $(seq 0 $(echo $RANDOM|head -c 2)) ; do /usr/bin/true ; done

while true
    do
        [ ! -f "/tmp/.X$RIM_DESKTOP_DISPLAY-lock" ] && \
            break
        RIM_DESKTOP_DISPLAY="$(( $RIM_DESKTOP_DISPLAY + 1 ))"
done

unset RUN_X
if [[ "$RUNTTY" =~ "tty" ]]
    then
        export DISPLAY=:$RIM_DESKTOP_DISPLAY
        info_msg "Xorg DISPLAY=$DISPLAY"
        unset XEPHYR RIM_XEPHYR_FULLSCREEN \
              RIM_XEPHYR_SIZE XEPHYR_DISPLAY
        if [ -x "/usr/lib/Xorg.wrap" ]
            then XORG="/usr/lib/Xorg.wrap"
        elif [ -x "/usr/bin/Xorg" ]
            then XORG="/usr/bin/Xorg"
        elif [ -x "/usr/bin/X" ]
            then XORG="/usr/bin/X"
        else XORG="/bin/Xorg"
        fi
        $XORG -nolisten tcp vt$XDG_VTNR $DISPLAY &
        export XORG_PID="$!"
        sleep 0.01
        is_pid "$XORG_PID" && RUN_X=1 || \
            error_msg "Failed to start Xorg!"
    else
        [ -n "$DISPLAY" ] && \
        XEPHYR=1||unset XEPHYR
fi

if [[ "$XEPHYR" == 1 || "$RIM_XEPHYR_FULLSCREEN" == 1 || -n "$RIM_XEPHYR_SIZE" ]]
    then
        XEPHYR_DISPLAY=:$RIM_DESKTOP_DISPLAY
        info_msg "Xephyr DISPLAY=$XEPHYR_DISPLAY"
        if [ "$RIM_XEPHYR_FULLSCREEN" == 1 ]
            then
                info_msg "Xephyr in full-screen mode"
        elif [ ! -n "$RIM_XEPHYR_SIZE" ]
            then
                RIM_XEPHYR_SIZE="1600x900"
                info_msg "Xephyr screen resolution: 1600x900"
        elif [ -n "$RIM_XEPHYR_SIZE" ]
            then
                RIM_XEPHYR_SIZE="$RIM_XEPHYR_SIZE"
                info_msg "Xephyr screen resolution: $RIM_XEPHYR_SIZE"
        fi
        Xephyr $([ "$RIM_XEPHYR_FULLSCREEN" == 1 ] && echo "-fullscreen"||echo "-screen $RIM_XEPHYR_SIZE") \
            +extension GLX +iglx -resizeable -br -title "RunImage Desktop [$XEPHYR_DISPLAY]" \
            -once -ac -name 'RunImage' $XEPHYR_DISPLAY &>/dev/null &
        export XEPHYR_PID="$!"
        sleep 0.01
        if is_pid "$XEPHYR_PID"
            then
                export DISPLAY=$XEPHYR_DISPLAY
                RUN_X=1
            else
                error_msg "Failed to start Xephyr!"
        fi
fi

EXEC_STATUS=1
if [ "$RUN_X" == 1 ]
    then
        run_xfce4() {
            unset -f run_xfce4
            unset WAYLAND_DISPLAY XDG_MENU_PREFIX XDG_SESSION_DESKTOP \
                DESKTOP_SESSION XDG_CURRENT_DESKTOP
            (try_count=0
            while is_pid "$XORG_PID" || is_pid "$XEPHYR_PID"
                do
                    if [ "$try_count" -le 5 ]
                        then
                            (( try_count++ ))
                            sleep 0.1
                            xfwm4 --replace --vblank=xpresent --sm-client-disable --compositor=on
                        else
                            error_msg "Failed to start xfwm4!"
                            break
                    fi
            done) &
            XFWM_PID="$!"
            unset -f is_pid
            sleep 0.1
            if [[ -n "$SYS_DISPLAY" && "$RIM_DESKTOP_UNCLIP" != 1 ]]
                then
                    xclipsync &
                    XCLIPSYNC_PID="$!"
                else
                    warn_msg "Clipboard synchronization is disabled!"
            fi
            sleep 0.1
            bash /etc/xdg/xfce4/xinitrc
            EXEC_STATUS="$?"
            kill $XCLIPSYNC_PID $XFWM_PID $XEPHYR_PID $XORG_PID 2>/dev/null
            kill $(pgrep -fa xclipfrom|grep "$DESKTOP_KEY"|awk '{print$1}') 2>/dev/null
            rm -rf "/tmp/.X$RIM_DESKTOP_DISPLAY-lock" 2>/dev/null
            [ "$XORG_PID" ] && reset
            return $EXEC_STATUS
        }
        info_msg "Launching RunImage Desktop..."
        export -f run_xfce4 is_pid
        dbus-run-session bash -c run_xfce4
        EXEC_STATUS="$?"
fi
exit $EXEC_STATUS
