#!/usr/bin/bash

is_exe_exist() { command -v "$@" &>/dev/null ; }

if is_exe_exist pacman
    then
        PACKEYRINGS=(archlinux-keyring)

        grep "^\[chaotic-aur\]" "/etc/pacman.conf" &>/dev/null && \
            PACKEYRINGS+=(chaotic-keyring)

        grep "^\[blackarch\]" "/etc/pacman.conf" &>/dev/null && \
            PACKEYRINGS+=(blackarch-keyring)

        pac -Sy "${PACKEYRINGS[@]}" --needed --noconfirm && \
        pactrans --sysupgrade --yolo||\
        exit 1
elif is_exe_exist apt
    then
        sudo apt update && \
        sudo apt upgrade -y||\
        exit 1
else
    error_msg "The package manager cannot be detected!"
    exit 1
fi
